MyBlog/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :users, except: [:new, :destroy]
  get '/register', to: 'users#new'
  root 'welcome#index'

end

MyBlog/app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

MyBlog/app/models/user.rb
class User < ActiveRecord::Base
  before_save {self.email = email.downcase}
  validates :name, presence: true, length: {minimum: 3,  maximum: 40}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\ d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 105},
                                      uniqueness: {case_sensitive: false},
                                      format: {with: VALID_EMAIL_REGEX}
  has_secure_password
end

MyBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

def logged_in?
  !!current_user
end

def requiere_user
  if !logged_in?
    flash[:danger] = "You must be logged in to perform that action"
    redirect_to posts_path
  end
end

end

MyBlog/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :requiere_user, except: [:show, :index, :like]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    Post.find(params[:id]).destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :text, :picture)
  end

end

MyBlog/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end

end

MyBlog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

MyBlog/app/helpers/application_helper.rb
module ApplicationHelper
end

MyBlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= yield %>

</body>
</html>

MyBlog/app/views/posts/edit.html.erb
<div class="new-form">

  <h1>Edit new post</h1>

    <%= form_for(@post, html:{ multipart: true }) do |f| %>
      <%= f.label :title %>
      <br>
      <div class="textfield">
        <%= f.text_field :title %>
      </div>
      <br>
      <%= f.label :text %>
      <br>
      <%= f.text_area :text, cols: 100, rows: 10  %>

      <br>
      <br>
      <span class="picture">
        <%= f.file_field :picture, accpet: 'image/jpeg,image/gif,image/png' %>
      </span>
      <%= f.submit 'Edit', class: "btn btn-success btn-lg" %>
    <% end %>
</div>

<script type="text/javascript">
  $('#post_picture').bind('change', function(){
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5)
    {
      alert('maximum file size is 5MB, please choose a smaller file');
    }
  });
</script>

MyBlog/app/views/posts/index.html.erb
<%= stylesheet_link_tag "grayscale" %>
<!-- Navigation -->
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand page-scroll" href="/#page-top">
                <i class="fa fa-play-circle"></i>  <span class="light">Alex</span> Terrazas
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul class="nav navbar-nav">
                <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li>
                    <a class="page-scroll" href="/#about">About</a>
                </li>
                <li>
                    <a class="page-scroll" href="/#download">Blog</a>
                </li>
                <li>
                    <a class="page-scroll" href="/#contact">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>


<div class="post-index">
  <% @posts.each do |post| %>
    <div class="ind-post">
      <%= image_tag(post.picture.url) if post.picture? %>
      <h3><%= post.title%></h3>
      <%= link_to "Read", post_path(post), class: "btn btn-success"%>
      <%= link_to "Edit", edit_post_path(post), class: "btn btn-warning"%>
      <%= link_to "Delete", post, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
    </div>
    <br>
  <%end%>
  <%= link_to "New Post", new_post_path, class: "btn btn-success btn-lg"%>
</div>

MyBlog/app/views/posts/new.html.erb
<div class="new-form">

  <h1>Create new post</h1>

    <%= form_for(@post, html:{ multipart: true }) do |f| %>
      <%= f.label :title %>
      <br>
      <div class="textfield">
        <%= f.text_field :title %>
      </div>
      <br>
      <%= f.label :text %>
      <br>
      <%= f.text_area :text, cols: 100, rows: 10  %>

      <br>
      <br>
      <span class="picture">
        <%= f.file_field :picture, accpet: 'image/jpeg,image/gif,image/png' %>
      </span>
      <%= f.submit 'Post', class: "btn btn-success btn-lg" %>
    <% end %>
</div>

<script type="text/javascript">
  $('#post_picture').bind('change', function(){
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5)
    {
      alert('maximum file size is 5MB, please choose a smaller file');
    }
  });
</script>

MyBlog/app/views/posts/show.html.erb
<h1 style="text-align: center; margin-top:3%;"><%= @post.title %></h1>
<hr>
<div class="post-image">
    <%= image_tag(@post.picture.url) if @post.picture? %>
</div>
<br>
<div class="post-text">
  <p><%= @post.text %><p>
</div>
<div class="back-button">
  <%= link_to "Back", posts_path, class: "btn btn-lg btn-danger"%>
</div>
<br>

MyBlog/app/views/users/new.html.erb
<div class="new-form">
  <h1>Register</h1>

    <%= form_for @user do |f| %>
      <%= f.label :name %>
      <br>
      <div class="textfield">
        <%= f.text_field :name %>
      </div>
      <br>
      <%= f.label :email %>
      <br>
      <div class="textfield">
        <%= f.text_field :email%>
      </div>  
      <br>
      <br>
      <%= f.submit 'Register', class: "btn btn-success btn-lg" %>
    <% end %>
</div>

MyBlog/app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <title>Grayscale - Start Bootstrap Theme</title>
    <%= stylesheet_link_tag "grayscale" %>
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">



</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                    <i class="fa fa-play-circle"></i>  <span class="light">Alex</span> Terrazas
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#download">Blog</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">Alex Terrazas</h1>
                        <p class="intro-text">OCR Elite Athlete from Mexico.<br>Adventure lover and Programmer.</p>
                        <a href="#about" class="btn btn-circle page-scroll">
                            <i class="fa fa-arrow-down"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- About Section -->
    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>About Me</h2>
                <p>My name is Alejandro Terrazas, I'm 22 years old and I live in Mexico City</p>
                <p>I have a passion for running, specially obstacle course races, I've been runnig for almost over 5 years but been into OCR for 4 years.</p>
                <p>I qualified for the 2015 Spartan Race World Championship and I'm working in qualifying again this year, I'm part of the elite group of Team Quintero, trained by Angel Quintero, #1 obstacle racer in Mexico and #6 in the world</p>
            </div>
        </div>
    </section>

    <!-- Download Section -->
    <section id="download" class="content-section text-center">
        <div class="download-section">
            <div class="container">
                <div class="col-lg-8 col-lg-offset-2">
                    <h2>Blog</h2>
                    <p>Visit my blog to know more about myself and a bit of my race stories</p>
                    <a href="/posts" class="btn btn-default btn-lg">Visit Blog</a>
                </div>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Contact </h2>
                <p>Follow me and contact me in my Social Networks</p>
                <p><a href="mailto:alex.terrazas.z@gmail.com">alex.terrazas.z@gmail.com</a>
                </p>
                <ul class="list-inline banner-social-buttons">
                    <li>
                        <a href="https://twitter.com/alex_terrazas94" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                    </li>
                    <li>
                        <a href="https://www.instagram.com/terry.alex/" class="btn btn-default btn-lg"><i class="fa fa-instagram fa-fw"></i> <span class="network-name">Instagram</span></a>
                    </li>
                    <li>
                        <a href="https://www.facebook.com/terry.alexocr" class="btn btn-default btn-lg"><i class="fa fa-facebook fa-fw"></i> <span class="network-name">Facebook</span></a>
                    </li>
                </ul>
            </div>
        </div>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
    </section>

    <!-- Footer -->
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; Alex Terrazas 2016</p>
        </div>
    </footer>



</body>

</html>